name: Build to Github Pages

on:
    push:
        branches:
            - ['main']
    pull_request:
        branches:
            - ['main']

    workflow_dispatch:

permissions:
    contents: read
    pages: write

concurrency:
    group: 'GH-Pages-Build'
    cancel-in-progress: true

jobs:
    Deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Install pnpm
              uses: pnpm/action-setup@v2
              with:
                version: 6.0.2

            - name: Cache .pnpm-store
              uses: actions/cache@v2
              with:
                  path: ~/.pnpm-store
                  key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-pnpm-

            - name: Install dependencies
              run: pnpm install

            - name: Build Vite site
              run: pnpm build

            - name: Deploy GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: dist
